[package]
name = "catr"
version = "0.1.0"
edition = "2021"
authors = ["Andy Baizon <dev@baizon.uk>"]

[dependencies]
clap = "4.0.30"

[dev-dependencies]
assert_cmd = "2.0.7"
predicates = "2.1.4"
rand = "0.8.5"